config/routes.rb
Rails.application.routes.draw do
  root to:'users#index'
  resources :users do
    collection {post :import}
    get :export_csv, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
require 'csv'
class User < ApplicationRecord

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      next if row.to_hash.values.any? { |value| value.nil? || value.empty? }

      User.create!(row.to_hash)
    end
  end


  def self.to_csv
    attributes = %w[id name steps pushups situps pullups created_at updated_at]
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map { |attr| user.send(attr) }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users=User.all
  end

  def import
    User.import(params[:file])
    redirect_to root_url, notice: 'User Data imported'
  end

  def export_csv
    users = User.all

    respond_to do |format|
      format.csv do
        send_data users.to_csv, filename: "users_data_#{Time.now.to_i}.csv"
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSVimport</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>  
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<table class="table w-75 p-3 ">
<%= flash[:notice] %>
  <thead class="table-dark">
    <tr> 
      <th>Name</th>
      <th>Steps</th>
      <th>Pushups</th>
      <th>Situps</th>
      <th>Pullups</th>
    </tr>
  </thead>
  <tbody>
    <% @users&.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.steps %></td>
        <td><%= user.pushups %></td>
        <td><%= user.situps %></td>
        <td><%= user.pullups %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <h3 class=" p-2 m-2">Import User Data</h3>
  <%= form_tag import_users_path,class:"p-2 m-2", multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag 'Import CSV',  class:"btn btn-success"  %>
  <% end %>
</div>
<%= link_to 'Export CSV', export_csv_users_path(format: :csv), class:"btn btn-success p-2 m-2" %>